### ISSUE TITLE
unit_06/figures/.ipynb_checkpoints needs to be deleted

### ISSUE THREAD

**Issue by angellmethod** [mids-w203/slides#1]
error: invalid path 'unit_06/figures/.ipynb_checkpoints/Icon?'

Hello - I get the above error when I try to clone this repo so I think even though `.ipynb_checkpoints` was added to the `.gitignore` file that this one still needs to get axed.

@d-alex-hughes

**Comment by d-alex-hughes** [comment]
@angellmethod, can you try now? If this fixes, can you close the issue? I committed straight to `main` because this was a pretty small fix that shouldn't break.
